############# English navigation ##############
# main menu
[[main]]
name = "Blog"
URL = "blog"
weight = 1

[[main]]
name = "Team"
URL = "team"
weight = 5

[[main]]
name = "FAQ"
URL = "faq"
weight = 15

[[main]]
name = "Career"
URL = "career"
weight = 20

# [[main]]
# weight = 50
# name = "Editions"
# hasChildren = true

[[main]]
parent = "Editions"
name = "Parent Edition"
URL = "parent"
weight = 1

[[main]]
parent = "Editions"
name = "Junior High Edition"
URL = "junior-high"
weight = 2

#Footer menu
[[footer]]
name = "Company History"
URL = "about"

[[footer]]
name = "About us"
URL = "about"

# [[footer]]
# name = "Contact us"
# URL = "contact"

# [[footer]]
# name = "Services"
# URL = "service"

[[footer]]
name = "Privacy Policy"
URL = "#"