############# English navigation ##############
# main menu
# [[main]]
# name = "About"
# URL = "about"
# weight = 2

# [[main]]
# name = "Service"
# URL = "service"
# weight = 3

[[main]]
name = "Blog"
URL = "blog"
weight = 1

[[main]]
name = "Parent Edition"
URL = "parent"
weight = 30

# [[main]]
# weight = 6
# name = "Pages"
# hasChildren = true

# [[main]]
# parent = "Pages"
# name = "Pricing"
# URL = "pricing"

[[main]]
# parent = "Pages"
name = "Team"
URL = "team"
weight = 5

[[main]]
# parent = "Pages"
name = "FAQ"
URL = "faq"
weight = 15

[[main]]
# parent = "Pages"
name = "Changelog"
URL = "changelog"
weight = 10

[[main]]
# parent = "Pages"
name = "Career"
URL = "career"
weight = 20

#Footer menu
[[footer]]
name = "Server Status"
URL = "https://vcassist.statuspage.io/"
weight = 10

[[footer]]
name = "Help Desk"
URL = "https://vc-assist.atlassian.net/servicedesk/customer/portals"
weight = 20

[[footer]]
name = "Parent Portal (Unreleased)"
URL = "#"
weight = 30

# [[footer]]
# name = "Contact us"
# URL = "contact"

# [[footer]]
# name = "Services"
# URL = "service"