############# English navigation ##############
# main menu
[[main]]
name = "Blog"
URL = "blog"
weight = 1

[[main]]
name = "Team"
URL = "team"
weight = 5

[[main]]
name = "Previous Members"
URL = "previous-members"
weight = 30

# [[main]]
# name = "Changelog"
# URL = "changelog"
# weight = 10

[[main]]
name = "FAQ"
URL = "faq"
weight = 15

#[[main]]
#name = "Career"
#URL = "career"
#weight = 20

#[[main]]
#weight = 50
#name = "Editions"
#hasChildren = true

#[[main]]
#parent = "Editions"
#name = "VC Assist: Parent Edition"
#URL = "parent"
#weight = 1

#[[main]]
#parent = "Editions"
#name = "Junior High Edition"
#URL = "junior-high"
#weight = 2

#Footer menu
[[footer]]
name = "Platform Status"
URL = "https://vcassist.statuspage.io/"
weight = 10

[[footer]]
name = "Helpdesk"
URL = "https://vc-assist.atlassian.net/servicedesk/customer/portals"
weight = 20

#[[footer]]
#name = "Parent Portal"
#URL = "https://parents.vcassist.org/login"
#weight = 30
