#################### default parameters ################################
# favicon
favicon = "images/favicon.ico"
# logo
logo = "images/logo.svg"
# OpenGraph / Twitter Card metadata
description = "VC Assist is a student-run, not-for-profit organization committed to ensuring academic success for all Valley Christian School (VCS) students."
author = "VC Assist Team"
image = "images/logo.svg" # this image will be used as fallback if a page has no image of its own
# contact info
address = "100 Skyway Drive <br> San Jose, CA 95111"
email = "hello@vcassist.org"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "Your ID"
# main sections
mainSections = ["blog"]
# search
search = true
# custom script on header
custom_script= ""


# Preloader
[preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "Sign Up"
link = "#"

# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = "" # replace this code with yours

# google map
[gmap]
enable = false
gmap_api = ""
map_latitude = ""
map_longitude = ""
map_marker = "images/marker.png"
map_marker_label = "VC Assist"
map_zoom = 17

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/vc_assist"

[[social]]
title = "discord"
icon = "fab fa-discord" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://discord.gg/dgwPTYZEku"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/vc-assist"

[[social]]
title = "youtube"
icon = "fab fa-youtube" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.youtube.com/@vcassist"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin-in" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/company/vc-assist"
